external_sources: []
imagemagick:
  enabled: false
exclude:
  - bin/
  - CONTRIBUTING.md
  - CUSTOMIZE.md
  - Dockerfile
  - docker-compose.yml
  - docker-compose-slim.yml
  - FAQ.md
  - Gemfile
  - Gemfile.lock
  - INSTALL.md
  - LICENSE
  - lighthouse_results/
  - package.json
  - package-lock.json
  - purgecss.config.js
  - README.md
  - readme_preview/
  - vendor
  - assets/jupyter/blog.ipynb